# Generated by Django 5.0.2 on 2024-08-08 20:01

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdef12345', length=5, max_length=10, prefix='', unique=True)),
                ('titulo', models.CharField(help_text='Categoria do Produto', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcd1234', length=5, max_length=10, prefix='', unique=True)),
                ('titulo', models.CharField(default='Titulo', max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_status', models.CharField(choices=[('rascunho', 'Rascunho'), ('desabilitado', 'Desabilitado'), ('publicado', 'Publicado')], max_length=12)),
                ('em_estoque', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sabores_terra.categoria')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
